<!-- FOOTER SECTION START ===== -->
<footer class="footer">
    <div class="footer-content">
        <p>&copy; 2026 AMIT INDUSTRIES. All rights reserved.</p>
        
        <div class="footer-socials">
            <a href="https://github.com/whitedevil-21" target="_blank" title="GitHub"><i class="fa-brands fa-github"></i></a>
            <a href="#" title="Instagram"><i class="fa-brands fa-instagram"></i></a>
            <a href="#" title="LinkedIn"><i class="fa-brands fa-linkedin-in"></i></a>
            <a href="mailto:amitdevi210@gmail.com" title="Email"><i class="fa-solid fa-envelope"></i></a>
        </div>
    </div>
</footer>
<!-- ===== FOOTER SECTION PART END ===== -->
</body>
</html>
