<!DOCTYPE html>
<html lang="en">
<head>

    <!-- ===== META TAGS ===== -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ===== ATTACH CSS OF MANUALLY ===== -->
    <link rel="stylesheet" href="CSS/style.css">
    <link rel="stylesheet" href="CSS/about.css">
    <link rel="stylesheet" href="CSS/blogs.css">
    <link rel="stylesheet" href="CSS/contact.css">

    <!-- ===== FONT AWESOME LIBRARY IMPORT ===== -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>HOME - AMIT INDUSTRIES</title>
</head>

<body>

    <!-- ===== HEADER DEPARTMENT START ===== -->
    <header>

        <!-- ===== NAVIGATION BAR START ===== -->
        <nav class="navbar">

            <!-- ===== LOGO DESIGN PART START ===== -->

            <div class="logo">AMIT INDUSTRIES</div>

            <!-- ===== LOGO DESIGN PART END ===== -->

            <!-- ===== NAVIGATION LINKS PART START ===== -->
            <ul class="nav-links">
                <li><a href="index.php">Home</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="blogs.php">Blogs</a></li>
                <li><a href="contact.php">Contact</a></li>
                <!-- <li><a href="form.php"><i class="fa-solid fa-user"></i></a></li> -->
            </ul>
            <!-- ===== NAVIGATION LINKS PART END ===== -->
        </nav>
        <!-- ===== NAVIGATION BAR PART END ===== -->
        <!-- ===== RIGHT CLICK DISABLED START ===== -->
        <script>
            // Disable right-click context menu globally
            document.addEventListener('contextmenu', function(event) {
                event.preventDefault();
            });
        </script>
        <!-- ===== RIGHT CLICK DISABLED END -->
    </header>
    <!-- ===== HEADER DEPARTMENT END ===== -->